[package]
name = "try-poem"
version = "0.1.0"
edition = "2021"

[dependencies]
poem = "3"
poem-openapi = { version = "5", features = ["swagger-ui"]}
serde = "1.0.210"
serde_json = "1.0.129"
tokio = { version = "1", features = ["full"] }
